version: "3"

services:
  web:
    container_name: web
    build:
      context: ./docker/build
      dockerfile: ./php${DOCKER_PHP_VERSION}/Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/project
      - ${DOCKER_APACHE_LOG_PATH}:/var/log/apache2
  db:
    container_name: db
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel
    ports:
      - "3306:3306"
    volumes:
      - ${DOCKER_MARIADB_DATA_PATH}:/var/lib/mysql
